module.exports = {
  alertTable: {
    EMPTY_FIELD: 'EMPTY_FIELD',
    CREATED: 'CREATED',
    FRIEND_EXISTS: 'FRIEND_EXISTS',
    DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
    FRIEND_REMOVED: 'FRIEND_REMOVED'
  }
}
