name: Node.js CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.example'
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04] # use of docker requires linux
        node-version: [12.18.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run heroku-postbuild
    - run: npm test
      env:
        CI: true
    - run: npm run lint
